---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 19838.
--- DateTime: 2022/10/12 10:49
---

local config = {
    ui = {
        [1] = {
            button = {
                juese = "res/ui/01/bottom/1900013010.png", --角色
                beibao = "res/ui/01/bottom/1900013011.png", --背包
                jineng = "res/ui/01/bottom/1900013012.png", --技能
                hanghui = "res/ui/01/bottom/1900013013.png", --行会
                zudui = "res/ui/01/bottom/1900013014.png", --组队
                jiaoyi = "res/ui/01/bottom/1900013015.png", --交易
                baitan = "res/ui/01/bottom/1900013016.png", --摆摊
                shezhi = "res/ui/01/bottom/1900013017.png", --设置
                tuichu = "res/ui/01/bottom/1900013018.png", --退出
                paimaihang = "res/ui/01/bottom/1900013019.png", --拍卖行
                qiangxing = "res/ui/01/bottom/1900013020.png", --强星
                fujin = "res/ui/01/bottom/1900013020.png", --附近
                jiaoyihang = "res/ui/01/bottom/jiaoyihang.png", --交易行
                haoyou = "res/ui/01/bottom/1900012583.png", --好友
                paihangbang = "res/ui/01/bottom/1900012587.png", --排行榜
                shejiao = "res/ui/01/bottom/1900012589.png", --社交
                youjian = "res/ui/01/bottom/1900012590.png", --邮件
                zhuansheng = "res/ui/01/bottom/1900012592.png", --转生
                zhaungban = "res/ui/01/bottom/1900012593.png", --装扮
                shangcheng = "res/ui/01/bottom/1900012595.png", --商城
                hecheng = "res/ui/01/bottom/1900012596.png", --合成
                cangku = "res/ui/01/bottom/1900012597.png", --仓库
                ronglu = "res/ui/01/bottom/1900012598.png", --熔炉
                qiehuan1 = "res/ui/01/bottom/1900012538.png", --切换1
                qiehuan2 = "res/ui/01/bottom/1900012580.png", --切换2
            }
        }
    }
}
return config