local config = {
	[1] = {
		Name = "鬼谷押镖",
		id = 3,
		BTime = "00$00",
		OTime = "23$59",
		Activitystart = "<font colorStyleID='16201'>未开始</font>",
		Activityinprogress = "<font colorStyleID='16202'>进行中</font>",
		Endofactivity = "<font colorStyleID='16207'>已结束</font>",
		Text = "<br><font color='#00FFFF'>鬼谷押镖，风险与利益共存。</font><br><font color='#00FFFF'>获得结束后按积分的多少以邮件的形式发放奖励！</font><br><font color='#00FFFF'>活动地图内，PK不红名，不掉狂暴！</font>",
		Time1 = {
			[1] = 1,
			[2] = 2,
			[3] = 3,
			[4] = 4,
			[5] = 5,
			[6] = 6,
			[7] = 7,
		},
		iconid = "img_3",
	},
	[2] = {
		Name = "鬼谷采集",
		id = 4,
		BTime = "00$00",
		OTime = "23$59",
		Activitystart = "<font colorStyleID='16201'>未开始</font>",
		Activityinprogress = "<font colorStyleID='16202'>进行中</font>",
		Endofactivity = "<font colorStyleID='16207'>已结束</font>",
		Text = "<br><font color='#00FFFF'>银蛋刷新在金蛋附近，银蛋采集后5分钟会再次刷新</font><br><font color='#00FFFF'>金蛋刷新在地图内的固定地点，金蛋15分钟刷新一次。</font><br><font color='#00FFFF'>活动地图内，PK不红名，不掉狂暴！</font>",
		Time1 = {
			[1] = 1,
			[2] = 2,
			[3] = 3,
			[4] = 4,
			[5] = 5,
			[6] = 6,
			[7] = 7,
		},
		iconid = "img_4",
	},
	[3] = {
		Name = "勇闯魔域",
		id = 2,
		BTime = "14$30",
		OTime = "15$00",
		Activitystart = "<font colorStyleID='16201'>未开始</font>",
		Activityinprogress = "<font colorStyleID='16202'>进行中</font>",
		Endofactivity = "<font colorStyleID='16207'>已结束</font>",
		Text = "<br><font color='#00FFFF'>活动开启后，地图内所有怪物3倍爆率！</font><br><font color='#00FFFF'>BOSS复活时间10分钟，小怪2分钟！</font><br><font color='#00FFFF'>活动地图专属产出侠侣材料</font><br><font color='#00FFFF'>沙漠通天法王[百倍爆率]，沙漠霸主[四十倍爆率]，黄泉教主和魔龙教主[二十倍爆率]，牛魔王和虹魔教主[十倍爆率]</font><br><font color='#00FFFF'>不掉狂暴，PK不红名！</font>",
		Time1 = {
			[1] = 1,
			[2] = 2,
			[3] = 3,
			[4] = 4,
			[5] = 5,
			[6] = 6,
			[7] = 7,
		},
		iconid = "img_2",
	},
	[4] = {
		Name = "大乱斗",
		id = 1,
		BTime = "19$30",
		OTime = "19$50",
		Activitystart = "<font colorStyleID='16201'>未开始</font>",
		Activityinprogress = "<font colorStyleID='16202'>进行中</font>",
		Endofactivity = "<font colorStyleID='16207'>已结束</font>",
		Text = "<br><font color='#00FFFF'>活动开启后，地图内会随机刷出大量的积分怪。</font><br><font color='#00FFFF'>地图内击杀玩家和积分怪都可获得积分。</font><br><font color='#00FFFF'>获得结束后按积分的多少以邮件的形式发放奖励！</font><br><font color='#00FFFF'>活动地图内，统一名称和模型，PK不红名，不掉狂暴！</font>",
		Gift = {
			[1] = {
				[1] = 201003,
				[2] = 1,
			},
			[2] = {
				[1] = 201013,
				[2] = 1,
			},
			[3] = {
				[1] = 8000401,
				[2] = 1,
			},
		},
		Time1 = {
			[1] = 1,
			[2] = 2,
			[3] = 3,
			[4] = 4,
			[5] = 5,
			[6] = 6,
			[7] = 7,
		},
		iconid = "img_1",
	},
	[5] = {
		Name = "沙城争霸",
		id = 6,
		BTime = "20$00",
		OTime = "21$00",
		Activitystart = "<font colorStyleID='16201'>未开始</font>",
		Activityinprogress = "<font colorStyleID='16202'>进行中</font>",
		Endofactivity = "<font colorStyleID='16207'>已结束</font>",
		Text = "<br/><font color='#00FFFF'>岁月不改当年激情！</font><br><font color='#00FFFF'>兄弟携手共战沙城！</font><br><font color='#00FFFF'>开服第三天开启攻城！过后每周六开启！</font><br><font color='#00FFFF'>未参与攻城帮会成员无奖励！</font><br><font color='#00FFFF'>攻沙前10分钟加入行会或者创建行会者无法参与此活动！</font>",
		Time1 = 6,
		iconid = "img_6",
	},
}
return config