---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 19838.
--- DateTime: 2022/10/11 14:55
---
SL = {}

---打印信息到控制台
function SL:print(...) end

---打开商城
function SL:OpenStoreUI() end

--json字符串解密
---@param jsonStr string
---@return table
function SL:JsonDecode(jsonStr) end
--json字符串加密
---@param jsonTbl table
---@return string
function SL:JsonEncode(jsonTbl) end

---发送提示信息
---@param str string
function SL:ShowSystemTips(str) end

---向服务器发送一个表单
---@param filename string文件名
---@param funcName string函数名
---@param param string参数
function SL:SubmitForm(filename, funcName, param) end

---获取角色基础属性
---@return roledata
function SL:GetRoleData() end

---注册游戏事件回调
---@param eventID string事件ID
---@param eventTag string事件描述
---@param eventCB fun回调函数
function SL:RegisterLUAEvent(eventID, eventTag, eventCB) end

---注销游戏事件回调
---@param eventID string	事件ID
---@param eventTag string	事件描述
function SL:UnRegisterLUAEvent(eventID, eventTag) end



