---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 19838.
--- DateTime: 2022/10/9 11:57
---@class size
---@field height 高度
---@field width 宽度
size = {}

---@class itemdata
---@field index integer物品模板id
---@field look boolean是否显示tips
---@field bgVisible boolean是否显示背景框
---@field count integer物品数量
---@field color 颜色
---@field checkPower boolean是否检查战力从而显示提升小箭头
---@field showModelEffect boolean只显示内观特效不显示背包特效
---@field onlyShowSFX boolean只显示道具特效其它都不显示
---@field noMouseTips boolean鼠标移入不显示tips
itemdata = {}

---@class roledata
---@field level 等级
---@field reinLv 转生等级
---@field job 职业
---@field sex 性别
---@field curHP 当前血量
---@field maxHP 最大血量
---@field curMP 当前蓝量
---@field maxMP 最大蓝量
---@field curExp 当前经验
---@field maxExp 最大经验
roledata = {}
